//
//  Model.swift
//  ToDoList
//
//  Created by Kyle Zeller on 8/31/23.
//

import Foundation

// MARK: - TaskState Enum
/// Represents the state of a task in the to-do list.
///
/// - workingOn: The task is currently in progress.
/// - todo: The task is yet to be started.
/// - done: The task has been completed.
enum TaskState: String, Codable, CaseIterable {
    case workingOn = "Working On"  // Indicates a task in progress
    case todo = "To-Do"            // Indicates a task yet to be started
    case done = "Done"             // Indicates a completed task
}

// MARK: - Task Struct
/// Represents a task in the to-do list.
///
/// Properties:
///   - `id`: A unique identifier for each task. It should not be `nil` or an empty string. Is generated by UUID.uuidstring()
///   - `title`: The title of the task, describing what needs to be done. It should not be `nil` or an empty string.
///   - `state`: The state of the task, represented by the `TaskState` enum.
struct Task: Identifiable, Codable {
    let id: String       // Unique identifier for the task
    var title: String    // Title or description of the task
    var state: TaskState // Current state of the task
}
